setting deployment for updates only

diff --git a/.github/workflows/to_s3.yml b/.github/workflows/to_s3.yml
--- a/.github/workflows/to_s3.yml
+++ b/.github/workflows/to_s3.yml
@@ -29,13 +29,44 @@ jobs:
           role-session-name: GitHub-OIDC-frontend-spear
           
       # Step 3: Files to S3
-          
-      # Option 2: Full (re)deployment
-
-      - name: Sync all files to S3
+            # Option 1: Upload only changed files to S3
+      - name: Get list of changed files
+        id: changes
         run: |
-          aws s3 sync ./ s3://spear-front-end --delete --exact-timestamps 
+          git fetch origin main
+          git diff --name-only HEAD^ HEAD > changed_files.txt
+          cat changed_files.txt
+          
+      # This will add files to the S3 bucket and also delete files in S3 not in the repo
+      - name: Sync changed files in S3
+        if: success()
+        run: |
+          while read file; do
+            echo "Attempting to upload $file..."
+            if ! aws s3 cp "$file" "s3://spear-front-end/$file" ; then
+              echo "File $file not found. Falling back to sync for deletion handling."
+              aws s3 sync ./ s3://spear-front-end --delete --exact-timestamps 
+            fi
+          done < changed_files.txt
         env:
           AWS_REGION: ${{ secrets.AWS_REGION }}
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 
+
+      - name: Invalidate CloudFront Cache
+        run: |
+          aws cloudfront create-invalidation \
+            --distribution-id ${{ secrets.SPEAR_CLOUDFRONT_DISTRIBUTION_ID}} \
+            --paths "/*"
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 
+          
+      # Option 2: Full (re)deployment
+
+      # - name: Sync all files to S3
+      #   run: |
+      #     aws s3 sync ./ s3://spear-front-end --delete --exact-timestamps 
+      #   env:
+      #     AWS_REGION: ${{ secrets.AWS_REGION }}
+      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 
           
